import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  oneimg: {
    width: width,
    alignSelf: 'center',
    height: height * 0.22,
    resizeMode: 'stretch',
    borderRadius: 0,
    marginVertical: height * 0.01,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  listbox: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
    height: height * 0.038,
    paddingHorizontal: height * 0.016,
    alignSelf: 'center',
    textAlign: 'center',
    borderRadius: 20,
    marginVertical: height * 0.015,

    // marginHorizontal: width * 0.01,
    // marginTop: height * 0.015,
    // marginBottom: height * 0.006,
    justifyContent: 'center',
  },
  listboxtext: {
    color: COLORS.primary,
    ...FONTS.sixHundred,
    fontSize: width * 0.032,
    marginBottom: -3,
  },
  // -------------------------------------
  faqBox: {
    flexDirection: 'row',
    width: width * 0.94,
    backgroundColor: COLORS.white,
    elevation: 3,
    alignSelf: 'center',
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.02,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginTop: height * 0.02,
  },
  faqtextBox: {
    width: width * 0.94,
    alignSelf: 'center',
    paddingHorizontal: width * 0.04,
    borderLeftWidth: 3,
    elevation: 3,
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderColor: COLORS.primary,
    marginBottom: height * 0.01,
    paddingVertical: height * 0.01,
  },
  uparrow: {
    width: width * 0.036,
    height: height * 0.018,
    resizeMode: 'contain',
    marginTop: height * 0.003,
    tintColor: COLORS.gray80,
  },
  faqtext: {
    color: COLORS.black,
    ...FONTS.fiveHundred,
    fontSize: width * 0.032,
    marginBottom: -3,
    width: width * 0.8,
  },
  // -----------------------------
  customerimg: {
    width: width * 0.14,
    height: width * 0.14,
    borderRadius: 80,
    marginRight: width * 0.025,
  },
  rightblue: {
    width: width * 0.04,
    height: height * 0.02,
    resizeMode: 'contain',
  },
  customerBox: {
    width: width * 0.64,
    paddingHorizontal: width * 0.03,
    paddingVertical: height * 0.02,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    borderWidth: 0.6,
    marginVertical: height * 0.016,
    marginHorizontal: width * 0.02,
    alignSelf: 'center',
    borderColor: COLORS.gray10,
  },
  customertext: {
    color: COLORS.black,
    fontSize: width * 0.035,
    ...FONTS.fiveHundred,
    marginBottom: -3,
  },
  customerContent: {
    color: COLORS.black,
    fontSize: width * 0.03,
    ...FONTS.fourHundred,
    marginBottom: -3,
    alignSelf: 'center',
    marginTop: height * 0.015,
    height: height * 0.23,
  },
  headcustomer: {
    color: COLORS.black,
    fontSize: width * 0.043,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginTop: height * 0.025,
    marginBottom: -4,
  },
  line: {
    width: width * 0.4,
    height: height * 0.018,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  fourimgmainbox: {
    alignSelf: 'center',
    width: width * 0.92,
    backgroundColor: '#fce9dc',
    flexWrap: 'wrap',
    flexDirection: 'row',
    borderRadius: 10,
    elevation: 4,
    marginVertical: height * 0.025,
  },
  fourimgbox: {
    width: width * 0.46,
    height: height * 0.2,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  fourimg: {
    alignSelf: 'center',
    width: width * 0.3,
    height: height * 0.1,
    resizeMode: 'contain',
  },
  fourtext: {
    alignSelf: 'center',
    width: width * 0.4,
    textAlign: 'center',
    color: COLORS.black,
    ...FONTS.sixHundred,
    marginTop: height * 0.01,
    fontSize: width * 0.035,
  },
});
