import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    width: width * 0.95,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
  },
  urlbox: {
    backgroundColor: '#F2F2F2',
    width: width * 0.9,
    alignSelf: 'center',
    padding: width * 0.03,
    borderRadius: 8,
    margin: height * 0.01,
  },
  url: {
    color: COLORS.gray80,
    fontSize: 10,
    ...FONTS.fiveHundred,
    textAlign: 'center',
  },
  btncopy: {
    height: height * 0.044,
    width: width * 0.3,
    margin: height * 0.01,
    alignSelf: 'flex-end',
  },
  pymtbox: {
    borderWidth: 1,
    borderColor: COLORS.gray10,
    borderRadius: 8,
    marginVertical: height * 0.01,
  },
  filter: {
    height: height * 0.03,
    width: width * 0.06,
    resizeMode: 'contain',
  },
  pymthist: {
    color: COLORS.gray80,
    fontSize: width * 0.035,
    ...FONTS.sixHundred,
    // marginTop: height * 0.012,
    marginBottom: -3,
  },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginVertical: height * 0.011,
    // alignSelf: 'center',
  },
  productdrop: {
    width: width * 0.29,
    height: height * 0.035,
    paddingHorizontal: width * 0.015,
    marginTop: height * 0.02,
  },
  btnrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: height * 0.015,
    alignSelf: 'flex-end',
    marginRight: width * 0.03,
  },
  number: {
    color: COLORS.gray80,
    fontSize: width * 0.028,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.fiveHundred,
    width: width * 0.1,
  },
  date: {
    color: COLORS.gray80,
    fontSize: width * 0.028,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.fiveHundred,
    width: width * 0.3,
  },
  pymt_name: {
    color: COLORS.gray80,
    fontSize: width * 0.028,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.fiveHundred,
    width: width * 0.36,
  },
  rupee: {
    color: COLORS.gray80,
    fontSize: width * 0.028,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.fiveHundred,
    width: width * 0.17,
  },
  heshrow: {
    flexDirection: 'row',
    alignItems: 'center',
    // borderBottomWidth: 1,
    // borderColor: COLORS.gray20,
    paddingVertical: width * 0.03,
  },
  hesh: {
    color: COLORS.gray50,
    fontSize: width * 0.031,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.sixHundred,
    width: width * 0.1,
  },
  heshdate: {
    color: COLORS.gray50,
    fontSize: width * 0.031,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.sixHundred,
    width: width * 0.3,
  },
  heshpymt_name: {
    color: COLORS.gray50,
    fontSize: width * 0.031,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.sixHundred,
    width: width * 0.35,
  },
  heshrupee: {
    color: COLORS.gray50,
    fontSize: width * 0.031,
    textAlign: 'center',
    alignSelf: 'center',
    ...FONTS.sixHundred,
    width: width * 0.19,
  },

  // numberbox: {
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   ...FONTS.sixHundred,
  //   width: width * 0.3,
  //   marginVertical: height * 0.015,
  // },
  // numbersystem: {
  //   color: COLORS.black,
  //   fontSize: width * 0.031,
  //   textAlign: 'center',
  //   ...FONTS.fiveHundred,
  // },
  // numbertext: {
  //   color: COLORS.black,
  //   fontSize: 14,
  //   textAlign: 'center',
  //   ...FONTS.fourHundred,
  // },
});
