import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    backgroundColor: COLORS.white,
    width: width * 0.94,
    alignSelf: 'center',
  },
  title: {
    color: COLORS.black,
    ...FONTS.sixHundred,
    fontSize: width * 0.04,
    marginBottom: -1,
    marginVertical: height * 0.01,
  },
  heading: {
    color: COLORS.black,
    ...FONTS.sixHundred,
    fontSize: width * 0.038,
    marginTop: height * 0.015,
    marginLeft: width * 0.032,
  },
  subtitle: {
    color: COLORS.gray60,
    ...FONTS.sixHundred,
    fontSize: width * 0.033,
    marginBottom: -3,
  },
  rate: {
    color: COLORS.green,
    ...FONTS.sixHundred,
    fontSize: width * 0.035,
    marginBottom: -4,
  },
  star: {
    width: width * 0.03,
    height: height * 0.015,
    resizeMode: 'cover',
    tintColor: COLORS.green,
    marginLeft: width * 0.008,
  },
  rating: {
    color: COLORS.gray50,
    ...FONTS.fiveHundred,
    fontSize: width * 0.031,
    marginBottom: -4,
    marginLeft: width * 0.03,
  },
  variantBox: {
    borderWidth: 1,
    borderColor: COLORS.gray20,
    width: width * 0.36,
    borderRadius: 10,
    marginBottom: height * 0.01,
  },
  variantmlBox: {
    width: width * 0.356,
    backgroundColor: '#F2F2F2',
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    alignSelf: 'center',
  },
  variantml: {
    color: COLORS.gray70,
    ...FONTS.fiveHundred,
    fontSize: width * 0.035,
    paddingLeft: width * 0.04,
    paddingVertical: height * 0.008,
  },
  variantmrp: {
    color: COLORS.black,
    ...FONTS.sixHundred,
    fontSize: width * 0.036,
    width: width * 0.18,
    textAlign: 'center',
  },
  variantprice: {
    color: COLORS.gray50,
    ...FONTS.sixHundred,
    fontSize: width * 0.036,
    textDecorationLine: 'line-through',
  },
  variantmlprimary: {
    color: COLORS.primary,
    ...FONTS.sixHundred,
    fontSize: width * 0.034,
    paddingLeft: width * 0.042,
  },
  include: {
    color: COLORS.gray30,
    ...FONTS.fiveHundred,
    fontSize: width * 0.03,
    marginTop: height * -0.01,
  },
  greenprice: {
    color: COLORS.green,
    ...FONTS.sixHundred,
    fontSize: width * 0.042,
    width: width * 0.2,
    marginLeft: width * 0.007,
  },
  mrp: {
    color: COLORS.gray40,
    ...FONTS.sixHundred,
    fontSize: width * 0.036,
    textDecorationLine: 'line-through',
    borderRightWidth: 1,
    borderColor: COLORS.gray40,
    paddingRight: width * 0.02,
    marginRight: width * 0.02,
  },
  off: {
    color: COLORS.primary,
    ...FONTS.sixHundred,
    fontSize: width * 0.034,
  },
  deliveraddress: {
    color: COLORS.gray50,
    ...FONTS.fiveHundred,
    fontSize: width * 0.033,
  },
  offerBox: {
    borderWidth: 1,
    width: width * 0.5,
    paddingHorizontal: width * 0.02,
    paddingVertical: width * 0.015,
    backgroundColor: '#FAFAFA',
    borderColor: COLORS.gray10,
    borderRadius: 10,
  },
  offericon: {
    width: width * 0.055,
    resizeMode: 'contain',
    height: height * 0.03,
    marginRight: width * 0.02,
  },
  offerblack: {
    color: COLORS.black,
    ...FONTS.fiveHundred,
    fontSize: width * 0.03,
  },
  offergreen: {
    color: COLORS.green,
    ...FONTS.fiveHundred,
    fontSize: width * 0.031,
  },
  iconarrow: {
    width: width * 0.018,
    resizeMode: 'stretch',
    height: height * 0.009,
    marginLeft: width * 0.012,
    tintColor: COLORS.green,
  },
  oneimg: {
    width: width,
    resizeMode: 'stretch',
    height: height * 0.22,
    alignSelf: 'center',
    borderRadius: 0,
    marginVertical: height * 0.01,
  },
  switchbox: {
    borderWidth: 1,
    borderColor: COLORS.gray10,
    height: height * 0.055,
    marginVertical: width * 0.025,
    borderRadius: 10,
    width: width * 0.37,
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    marginLeft: width * 0.022,
    marginRight: width * 0.02,
  },
  switchtext: {
    textAlign: 'center',
    ...FONTS.sixHundred,
    color: COLORS.gray60,
    fontSize: width * 0.032,
    marginBottom: -2,
  },
  activeswitch: {
    shadowColor: COLORS.primary,
    borderWidth: 0,
    borderBottomWidth: 2,
    elevation: 3,
    borderBottomColor: COLORS.primary,
    shadowOpacity: 0.9,
    shadowRadius: 8,
    shadowOffset: {
      height: 7,
      width: 5,
    },
  },
  switchtitle: {
    ...FONTS.fiveHundred,
    color: COLORS.gray60,
    fontSize: width * 0.032,
    width: width * 0.94,
    alignSelf: 'center',
    marginVertical: height * 0.01,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: height * 0.005,
  },

  faqBox: {
    flexDirection: 'row',
    width: width * 0.94,
    backgroundColor: COLORS.white,
    elevation: 3,
    alignSelf: 'center',
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.02,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginTop: height * 0.02,
  },
  faqtextBox: {
    width: width * 0.94,
    alignSelf: 'center',
    paddingHorizontal: width * 0.04,
    borderLeftWidth: 3,
    elevation: 3,
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderColor: COLORS.primary,
    marginBottom: height * 0.01,
  },
  uparrow: {
    width: width * 0.036,
    height: height * 0.018,
    resizeMode: 'contain',
    marginTop: height * 0.003,
    tintColor: COLORS.gray80,
  },
  faqtext: {
    color: COLORS.black,
    ...FONTS.fiveHundred,
    fontSize: width * 0.032,
    marginBottom: -3,
    width: width * 0.8,
  },

  headcustomer: {
    color: COLORS.black,
    fontSize: width * 0.043,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginTop: height * 0.025,
    marginBottom: -4,
  },
  line: {
    width: width * 0.4,
    height: height * 0.018,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  fourimgbox: {
    width: width * 0.25,
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: height * 0.03,
  },
  fourimg: {
    alignSelf: 'center',
    width: width * 0.12,
    height: height * 0.05,
    resizeMode: 'contain',
  },
  fourtext: {
    alignSelf: 'center',
    fontSize: width * 0.025,
    textAlign: 'center',
    color: COLORS.black,
    ...FONTS.sixHundred,
    height: height * 0.04,
    marginTop: height * 0.006,
  },
  readall: {
    fontSize: width * 0.036,
    color: COLORS.gray60,
    ...FONTS.sixHundred,
    marginLeft: width * 0.03,
  },
  starbox: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: width * 0.87,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: height * 0.005,
  },
  usercount: {
    fontSize: 11.5,
    fontFamily: FONTS.medium,
    color: COLORS.black,
    width: width * 0.25,
  },
  starstyle: {
    width: width * 0.26,
    alignItems: 'flex-start',
  },
  starmainbox: {
    borderWidth: 1,
    width: width * 0.93,
    alignSelf: 'center',
    paddingVertical: height * 0.01,
    borderColor: COLORS.gray10,
    borderRadius: 8,
    marginBottom: height * 0.02,
  },
  raterowbox: {
    borderWidth: 1,
    width: width * 0.93,
    alignSelf: 'center',
    paddingVertical: height * 0.01,
    borderColor: COLORS.gray10,
    borderRadius: 8,
    marginVertical: height * 0.02,
    paddingHorizontal: height * 0.025,
  },
  input: {
    width: width * 0.82,
    borderRadius: 6,
    marginTop: height * 0.015,
  },
  ratetext: {
    color: COLORS.black,
    fontSize: width * 0.032,
    ...FONTS.sixHundred,
    width: width * 0.45,
  },
  circlebox: {
    alignSelf: 'center',
    width: width * 0.23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circletext: {
    color: COLORS.black,
    fontSize: width * 0.025,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginTop: height * 0.006,
  },
  ReviewBox: {
    width: width * 0.92,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: height * 0.02,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
  },
  Reviewimg: {
    marginRight: width * 0.03,
    height: width * 0.11,
    width: width * 0.11,
    borderRadius: 80,
    resizeMode: 'stretch',
  },
  text1: {
    width: width * 0.78,
    ...FONTS.fiveHundred,
    color: COLORS.black,
    fontSize: width * 0.032,
    marginBottom: -4,
  },
  reviewsubtext: {
    width: width * 0.78,
    ...FONTS.fiveHundred,
    color: COLORS.gray60,
    fontSize: width * 0.03,
    marginBottom: -4,
  },
  bottomrow: {
    elevation: 3,
    width: width,
    backgroundColor: COLORS.white,
    paddingVertical: height * 0.01,
    flexDirection: 'row',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'space-around',
  },
});
